### ISSUE TITLE
NODE_ENV boost

### ISSUE THREAD

**Issue by nikolaymatrosov** [fullfs/Perfomance#1]
![2015-07-25 12-21-36 mingw32 c projects perfomance server react build](https://cloud.githubusercontent.com/assets/1625055/8888272/8d6fcbf0-32c8-11e5-8694-409c8d5fbc6c.png)

**Comment by fullfs** [comment]
Ну вот, я всё таки что-то упустил )) буду проверять всё заново, спасибо )

**Comment by nikolaymatrosov** [comment]
Апдейт react до 0.14 beta дает еще больший прирост в скорости. У меня вышло
~850ms в production mode.

**Comment by fullfs** [comment]
@nikolaymatrosov о, ну это здорово! Видимо ребята работают над этим.
Однако, хочу обратить твоё внимание на пару моментов:
1. 850ms для продакшна это всё равно очень много. Даже если брать страницу меньше и если бы это было всего 300ms, например. Это 300ms которые блокируют поток полностью, т.е. ядро при исполнении функции рендеринга больше ничего делать не сможет
2. jsdom - самый медленный инструмент для эмуляции dom на сервере. Есть значительно более быстрые решения. Более того, те 5 с лишним секунд, которые получались при получении разметки в кейсе vue.js + jsdom почти целиком приходились на запуск jsdom. Сама разметка генерировалась около 60-100мс. При определённых усилиях можно построить систему, в которой не придётся запускать новую копию jsdom (или другого инструмента) под каждый запрос. Будут свои проблемы, но в целом можно тоже добиться намного меньшей времени отдачи. Просто я не стал прорабатывать это направление

**Comment by nikolaymatrosov** [comment]
Я понимаю. Просто хотел указать на неточности в докладе. Ну и на то что
приведенные цифры устарели.

**Comment by fullfs** [comment]
@nikolaymatrosov окей ) очень признателен за твои уточнения ) уточнил на всякий случай )
